// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // AxisLists
    [Table("AxisLists", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class AxisList : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_AxisList", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"InquiryId", Order = 2, TypeName = "int")]
        [Index(@"IX_AxisLists", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Inquiry ID")]
        public int InquiryId { get; set; } // InquiryId

        [Column(@"Title", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Title")]
        public string Title { get; set; } // Title (length: 100)

        [Column(@"Deleted", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Deleted")]
        public bool Deleted { get; set; } = false; // Deleted

        // Reverse navigation

        /// <summary>
        /// Child Axes where [Axes].[AxisListId] point to this entity (FK_Axis_AxisList)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Axis> Axes { get; set; } = new System.Collections.Generic.List<Axis>(); // Axes.FK_Axis_AxisList

        // Foreign keys

        /// <summary>
        /// Parent Inquiry pointed by [AxisLists].([InquiryId]) (FK_AxisLists_Inquiries)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("InquiryId"), Required] public virtual Inquiry Inquiry { get; set; } // FK_AxisLists_Inquiries
    }

}
// </auto-generated>
