// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // Choices
    [Table("Choices", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Choice : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Choices", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"DemographicId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Demographic ID")]
        public int DemographicId { get; set; } // DemographicId

        [Column(@"Text", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Text")]
        public string Text { get; set; } // Text (length: 100)

        [Column(@"AllowedKey", Order = 4, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Allowed key")]
        public byte AllowedKey { get; set; } // AllowedKey

        [Column(@"Deleted", Order = 5, TypeName = "bit")]
        [Required]
        [Display(Name = "Deleted")]
        public bool Deleted { get; set; } = false; // Deleted

        // Foreign keys

        /// <summary>
        /// Parent Demographic pointed by [Choices].([DemographicId]) (FK_Choices_Demographics)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("DemographicId"), Required] public virtual Demographic Demographic { get; set; } // FK_Choices_Demographics
    }

}
// </auto-generated>
