// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // Demographics
    [Table("Demographics", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Demographic : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Demographics", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"InquiryId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Inquiry ID")]
        public int InquiryId { get; set; } // InquiryId

        [Column(@"Question", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Question")]
        public string Question { get; set; } // Question (length: 100)

        [Column(@"Deleted", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Deleted")]
        public bool Deleted { get; set; } // Deleted

        // Reverse navigation

        /// <summary>
        /// Child Choices where [Choices].[DemographicId] point to this entity (FK_Choices_Demographics)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Choice> Choices { get; set; } = new System.Collections.Generic.List<Choice>(); // Choices.FK_Choices_Demographics

        // Foreign keys

        /// <summary>
        /// Parent Inquiry pointed by [Demographics].([InquiryId]) (FK_Demographics_Inquiries)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("InquiryId"), Required] public virtual Inquiry Inquiry { get; set; } // FK_Demographics_Inquiries
    }

}
// </auto-generated>
