// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    public interface IEntityDB : System.IDisposable
    {
        System.Data.Entity.DbSet<Axis> Axes { get; set; } // Axes
        System.Data.Entity.DbSet<AxisList> AxisLists { get; set; } // AxisLists
        System.Data.Entity.DbSet<Choice> Choices { get; set; } // Choices
        System.Data.Entity.DbSet<Demographic> Demographics { get; set; } // Demographics
        System.Data.Entity.DbSet<Inquiry> Inquiries { get; set; } // Inquiries
        System.Data.Entity.DbSet<Member> Members { get; set; } // Members
        System.Data.Entity.DbSet<Participant> Participants { get; set; } // Participants
        System.Data.Entity.DbSet<Result> Results { get; set; } // Results
        System.Data.Entity.DbSet<ScaleEntry> ScaleEntries { get; set; } // ScaleEntry
        System.Data.Entity.DbSet<ScaleList> ScaleLists { get; set; } // ScaleLists
        System.Data.Entity.DbSet<Topic> Topics { get; set; } // Topics
        System.Data.Entity.DbSet<TopicList> TopicLists { get; set; } // TopicLists
        System.Data.Entity.DbSet<User> Users { get; set; } // Users
        System.Data.Entity.DbSet<Vote> Votes { get; set; } // Votes

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
