// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // Inquiries
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Inquiry_Map : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Inquiry>
    {
        public Inquiry_Map()
            : this("dbo")
        {
        }

        public Inquiry_Map(string schema)
        {
            Property(x => x.Title).IsUnicode(false);
            Property(x => x.State).IsUnicode(false);
            Property(x => x.FacilitatorName).IsOptional().IsUnicode(false);
            Property(x => x.FacilitatorId).IsOptional();
            Property(x => x.InquiryOpens).IsOptional();
            Property(x => x.EvaluationStarts).IsOptional();
            Property(x => x.EvaluationEnds).IsOptional();

        }
    }

}
// </auto-generated>
