// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // Inquiries
    [Table("Inquiries", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Inquiry : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Inquiries", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"MemberId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Member ID")]
        public int MemberId { get; set; } // MemberId

        [Column(@"Title", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Title")]
        public string Title { get; set; } // Title (length: 100)

        [Column(@"State", Order = 4, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "State")]
        public string State { get; set; } = "SETUP"; // State (length: 20)

        [Column(@"FacilitatorName", Order = 5, TypeName = "varchar")]
        [MaxLength(101)]
        [StringLength(101)]
        [Display(Name = "Facilitator name")]
        public string FacilitatorName { get; set; } // FacilitatorName (length: 101)

        [Column(@"FacilitatorId", Order = 6, TypeName = "int")]
        [Display(Name = "Facilitator ID")]
        public int? FacilitatorId { get; set; } // FacilitatorId

        ///<summary>
        /// allows participants to connect
        ///</summary>
        [Column(@"InquiryOpens", Order = 7, TypeName = "date")]
        [DataType(DataType.Date)]
        [Display(Name = "Inquiry opens")]
        public System.DateTime? InquiryOpens { get; set; } // InquiryOpens

        ///<summary>
        /// allows voting
        ///</summary>
        [Column(@"EvaluationStarts", Order = 8, TypeName = "date")]
        [DataType(DataType.Date)]
        [Display(Name = "Evaluation starts")]
        public System.DateTime? EvaluationStarts { get; set; } // EvaluationStarts

        ///<summary>
        /// voting ends, results viewing begins
        ///</summary>
        [Column(@"EvaluationEnds", Order = 9, TypeName = "date")]
        [DataType(DataType.Date)]
        [Display(Name = "Evaluation ends")]
        public System.DateTime? EvaluationEnds { get; set; } // EvaluationEnds

        ///<summary>
        /// inquiry archived
        ///</summary>
        [Column(@"InquiryCloses", Order = 10, TypeName = "date")]
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Inquiry closes")]
        public System.DateTime InquiryCloses { get; set; } // InquiryCloses

        [Column(@"Deleted", Order = 11, TypeName = "bit")]
        [Required]
        [Display(Name = "Deleted")]
        public bool Deleted { get; set; } = false; // Deleted

        // Reverse navigation

        /// <summary>
        /// Child AxisLists where [AxisLists].[InquiryId] point to this entity (FK_AxisLists_Inquiries)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<AxisList> AxisLists { get; set; } = new System.Collections.Generic.List<AxisList>(); // AxisLists.FK_AxisLists_Inquiries
        /// <summary>
        /// Child Demographics where [Demographics].[InquiryId] point to this entity (FK_Demographics_Inquiries)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Demographic> Demographics { get; set; } = new System.Collections.Generic.List<Demographic>(); // Demographics.FK_Demographics_Inquiries
        /// <summary>
        /// Child Participants where [Participants].[InquiryId] point to this entity (FK_Participants_Inquiries)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Participant> Participants { get; set; } = new System.Collections.Generic.List<Participant>(); // Participants.FK_Participants_Inquiries
        /// <summary>
        /// Child Results where [Results].[InquiryId] point to this entity (FK_Results_Inquiries)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Result> Results { get; set; } = new System.Collections.Generic.List<Result>(); // Results.FK_Results_Inquiries
        /// <summary>
        /// Child TopicLists where [TopicLists].[InquiryId] point to this entity (FK_TopicList_Inquiries)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<TopicList> TopicLists { get; set; } = new System.Collections.Generic.List<TopicList>(); // TopicLists.FK_TopicList_Inquiries
        /// <summary>
        /// Child Votes where [Votes].[InquiryId] point to this entity (FK_Votes_Inquiries)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Vote> Votes { get; set; } = new System.Collections.Generic.List<Vote>(); // Votes.FK_Votes_Inquiries

        // Foreign keys

        /// <summary>
        /// Parent Member pointed by [Inquiries].([MemberId]) (FK_Inquiries_Members)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("MemberId"), Required] public virtual Member Member { get; set; } // FK_Inquiries_Members
    }

}
// </auto-generated>
