// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // Members
    [Table("Members", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Member : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Members", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"UserId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "User ID")]
        public int UserId { get; set; } // UserId

        [Column(@"MemberName", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(101)]
        [StringLength(101)]
        [Display(Name = "Member name")]
        public string MemberName { get; set; } // MemberName (length: 101)

        [Column(@"Suspended", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Suspended")]
        public bool Suspended { get; set; } // Suspended

        [Column(@"SuspendedReason", Order = 5, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Suspended reason")]
        public string SuspendedReason { get; set; } // SuspendedReason (length: 1000)

        [Column(@"Json", Order = 6, TypeName = "varchar(max)")]
        [Display(Name = "Json")]
        public string Json { get; set; } // Json

        // Reverse navigation

        /// <summary>
        /// Child Inquiries where [Inquiries].[MemberId] point to this entity (FK_Inquiries_Members)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Inquiry> Inquiries { get; set; } = new System.Collections.Generic.List<Inquiry>(); // Inquiries.FK_Inquiries_Members

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Members].([UserId]) (FK_Members_Users)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("UserId"), Required] public virtual User User { get; set; } // FK_Members_Users
    }

}
// </auto-generated>
