// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // Participants
    [Table("Participants", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Participant : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Participants", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"UserId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "User ID")]
        public int UserId { get; set; } // UserId

        [Column(@"InquiryId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Inquiry ID")]
        public int InquiryId { get; set; } // InquiryId

        [Column(@"ParticipantName", Order = 4, TypeName = "varchar")]
        [MaxLength(101)]
        [StringLength(101)]
        [Display(Name = "Participant name")]
        public string ParticipantName { get; set; } // ParticipantName (length: 101)

        [Column(@"FilteredOut", Order = 5, TypeName = "bit")]
        [Required]
        [Display(Name = "Filtered out")]
        public bool FilteredOut { get; set; } = false; // FilteredOut

        [Column(@"NotParticipating", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Not participating")]
        public bool NotParticipating { get; set; } = false; // NotParticipating

        // Foreign keys

        /// <summary>
        /// Parent Inquiry pointed by [Participants].([InquiryId]) (FK_Participants_Inquiries)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("InquiryId"), Required] public virtual Inquiry Inquiry { get; set; } // FK_Participants_Inquiries

        /// <summary>
        /// Parent User pointed by [Participants].([UserId]) (FK_Participants_Users)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("UserId"), Required] public virtual User User { get; set; } // FK_Participants_Users
    }

}
// </auto-generated>
