// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // ScaleEntry
    [Table("ScaleEntry", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ScaleEntry : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ScaleEntry", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"ScaleListId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Scale list ID")]
        public int ScaleListId { get; set; } // ScaleListId

        [Column(@"Text", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Text")]
        public string Text { get; set; } // Text (length: 50)

        [Column(@"AllowedKey", Order = 4, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Allowed key")]
        public byte AllowedKey { get; set; } // AllowedKey

        [Column(@"TopicAssignmentGroup", Order = 5, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Topic assignment group")]
        public byte TopicAssignmentGroup { get; set; } // TopicAssignmentGroup

        [Column(@"Points", Order = 6, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Points")]
        public byte Points { get; set; } // Points

        [Column(@"GroupBreakBefore", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Group break before")]
        public bool GroupBreakBefore { get; set; } = false; // GroupBreakBefore

        [Column(@"Deleted", Order = 8, TypeName = "bit")]
        [Required]
        [Display(Name = "Deleted")]
        public bool Deleted { get; set; } = false; // Deleted

        // Foreign keys

        /// <summary>
        /// Parent ScaleList pointed by [ScaleEntry].([ScaleListId]) (FK_ScaleEntry_ScaleList)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("ScaleListId"), Required] public virtual ScaleList ScaleList { get; set; } // FK_ScaleEntry_ScaleList
    }

}
// </auto-generated>
