// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cnx.Shared.DAL.Models
{
    using Newtonsoft.Json;

    // TopicLists
    [Table("TopicLists", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class TopicList : EntityBaseClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_TopicList", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"InquiryId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Inquiry ID")]
        public int InquiryId { get; set; } // InquiryId

        [Column(@"Title", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Title")]
        public string Title { get; set; } // Title (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child Topics where [Topics].[TopicListId] point to this entity (FK_Topic_TopicList)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Topic> Topics { get; set; } = new System.Collections.Generic.List<Topic>(); // Topics.FK_Topic_TopicList

        // Foreign keys

        /// <summary>
        /// Parent Inquiry pointed by [TopicLists].([InquiryId]) (FK_TopicList_Inquiries)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("InquiryId"), Required] public virtual Inquiry Inquiry { get; set; } // FK_TopicList_Inquiries
    }

}
// </auto-generated>
